export const CREATE_CHECK = 'CREATE_CHECK';

export const ADD_DRINK = 'ADD_DRINK';
export const ADD_DESSERT = 'ADD_DESSERT';

export const SET_PAYMENT_TYPE = 'SET_PAYMENT_TYPE';
export const SET_ORDER_TYPE = 'SET_ORDER_TYPE';
export const PROCESS_CHECKOUT = 'PROCESS_CHECKOUT';

export const LOAD_ITEMS = 'LOAD_ITEMS';
export const LOAD_ITEMS_FULFILLED = 'LOAD_ITEMS_FULFILLED';
export const LOAD_ITEMS_REJECTED = 'LOAD_ITEMS_REJECTED';

export const SHOW_BUSY = "SHOW_BUSY";

export const APPEND_DATA = 'APPEND_DATA';
export const APPEND_DATA_FULFILLED = 'APPEND_DATA_FULFILLED';
export const APPEND_DATA_REJECTED = 'APPEND_DATA_REJECTED';

export const UPDATE_DATA = 'UPDATE_DATA';
export const UPDATE_DATA_FULFILLED = 'UPDATE_DATA_FULFILLED';
export const UPDATE_DATA_REJECTED = 'UPDATE_DATA_REJECTED';

export const LOG_DATA = 'LOG_DATA';
export const CLEAR_LOG = 'CLEAR_LOG';