export const CREATE_CHECK = 'CREATE_CHECK';

export const ADD_DRINK = 'ADD_DRINK';

export const ADD_DESSERT = 'ADD_DESSERT';

export const PROCESS_CHECKOUT = 'PROCESS_CHECKOUT';

export const LOAD_ITEMS = 'LOAD_ITEMS';
export const LOAD_ITEMS_FULFILLED = 'LOAD_ITEMS_FULFILLED';
export const LOAD_ITEMS_REJECTED = 'LOAD_ITEMS_REJECTED';

export const SHOW_BUSY = "SHOW_BUSY";