export const CREATE_CHECK = 'CREATE_CHECK';

export const ADD_DRINK = 'ADD_DRINK';
export const ADD_DESSERT = 'ADD_DESSERT';

export const DELETE_DRINK = 'DELETE_DRINK';
export const DELETE_DESSERT = 'DELETE_DESSERT';

export const SET_PAYMENT_TYPE = 'SET_PAYMENT_TYPE';
export const SET_ORDER_TYPE = 'SET_ORDER_TYPE';
export const SELECT_SALE = 'SELECT_SALE';
export const PROCESS_CHECKOUT = 'PROCESS_CHECKOUT';
export const SET_IS_PAID = 'SET_IS_PAID';
export const SELECT_STAFF = 'SELECT_STAFF';

export const LOAD_ITEMS = 'LOAD_ITEMS';
export const LOAD_ITEMS_FULFILLED = 'LOAD_ITEMS_FULFILLED';
export const LOAD_ITEMS_REJECTED = 'LOAD_ITEMS_REJECTED';

export const SHOW_BUSY = "SHOW_BUSY";

export const APPEND_DATA = 'APPEND_DATA';
export const APPEND_DATA_FULFILLED = 'APPEND_DATA_FULFILLED';
export const APPEND_DATA_REJECTED = 'APPEND_DATA_REJECTED';

export const UPDATE_DATA = 'UPDATE_DATA';
export const UPDATE_DATA_FULFILLED = 'UPDATE_DATA_FULFILLED';
export const UPDATE_DATA_REJECTED = 'UPDATE_DATA_REJECTED';

export const LOG_DATA = 'LOG_DATA';
export const CLEAR_LOG = 'CLEAR_LOG';
export const CANCEL = 'CANCEL';

export const CLEAR_ERROR = 'CLEAR_ERROR';

export const SET_LAST_ID = 'SET_LAST_ID';

export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION';

export const CHANGE_PROFILE = 'CHANGE_PROFILE';

export const SET_DAILY_PERCENT = 'SET_DAILY_PERCENT';

export const SET_DRINKS_COUNT = 'SET_DRINKS_COUNT';